### ISSUE TITLE
 Improve columns mapping structure

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/generate-bom#3]
In BOM generation, we've found that the columns mapping is hard for people to understand at first. The structure of the columns mapping - a dictionary with the keys being the name of the columns and the value being a list of attributes to check - has a lot of implicit meaning that makes it easy for us as developers to work with but harder to understand. 

Since we are changing the language for the configuration, we could also change the columns mapping to look more like:

```yaml

columns:
  - name: Designator
    attributes_to_check: Designator
  - name: Manufacturer
    attributes_to_check:
      - Manufacturer
      - MFN
  - name: Part Number
    attributes_to_check:
      - Part
      - PN
      - _part_id
```

**Comment by shrik450** [comment]
@kdumontnu Do you think this is worth picking up when switching the configuration to YAML?

**Comment by kdumontnu** [comment]
Yes, I think it's a good change to include at the same time.

My only hesitation is still in whether we want to limit columns to user-attributes and other component attributes that we prefix with `_`. Since I don't want to increase the scope any further, I think we can kick that to future development.

I would rename `attributes_to_check` to `part_attributes`. An alternative could be to use an unstructured schema to reduce the number of keywords users have to remember, like:

```
columns:
  - Designator:
    - Designator
  - Manufacturer:
    - Manufacturer
    - MFN
  - Part Number:
    - Part
    - PN
    - _part_id
```
